import type { Metadata } from "next";
import Layout from "@/components/Layout";

import "./globals.css";
import ShoppingCartContextProvider from "@/context/ShoppingCartContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ShoppingCartContextProvider>
          <Layout>
            {children}
          </Layout>
        </ShoppingCartContextProvider>
      </body>
    </html>
  );
}
